ArgumentError: wrong number of arguments (given 1, expected 0) (#1)
This happens if a model has a `method` attribute, so the model's attribute is called instead of `Object.method`. This is just a quick fix until we can rename the attributes in our models, since this won't be merged into the main repo, as explained here: https://github.com/DmitryTsepelev/store_model/pull/122#issuecomment-1168584550